name: "Static Analysis"

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  phpstan:
    name: PHPStan (PHP ${{ matrix.php-version }}, ${{ matrix.dependency-versions }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.1'
            dependency-versions: lowest
          - php-version: '8.5'
            dependency-versions: highest

    steps:
    - name: Repository checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v2
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
      with:
        dependency-versions: ${{ matrix.dependency-versions }}

    - name: Run PHPStan
      run: composer run-script phpstan -- --no-progress
